// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAGfvh1dUBEs49mIrX4BbBiPPj1gZfvVtc',
    appId: '1:1054091003256:web:98785388b499531f03f48d',
    messagingSenderId: '1054091003256',
    projectId: 'fir-notifications-b23c4',
    authDomain: 'fir-notifications-b23c4.firebaseapp.com',
    storageBucket: 'fir-notifications-b23c4.firebasestorage.app',
    measurementId: 'G-RSRM15H7X7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDpSrVNTQmQz-YabpCK4LJL5QSbp8K-j0k',
    appId: '1:1054091003256:android:0857184e5594129f03f48d',
    messagingSenderId: '1054091003256',
    projectId: 'fir-notifications-b23c4',
    storageBucket: 'fir-notifications-b23c4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCFQNoZDX7pjUn83NMCGr1BlAv8I-52Tfc',
    appId: '1:1054091003256:ios:2400a93d3b6121ed03f48d',
    messagingSenderId: '1054091003256',
    projectId: 'fir-notifications-b23c4',
    storageBucket: 'fir-notifications-b23c4.firebasestorage.app',
    iosBundleId: 'com.example.firebaseNotification',
  );
}
